import {useEffect,useRef,useState} from 'react';
import {Save,X} from 'lucide-react';

export default function MaskEditorModal({imageUrl,maskUrl,onClose,onSave}:{imageUrl:string;maskUrl?:string;onClose:()=>void;onSave:(file:File)=>Promise<void>}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[erase,setErase]=useState(false),[size,setSize]=useState(28),[busy,setBusy]=useState(false);
 useEffect(()=>{const base=new Image();base.crossOrigin='anonymous';base.onload=()=>{const c=canvas.current!;c.width=base.naturalWidth;c.height=base.naturalHeight;const ctx=c.getContext('2d')!;ctx.fillStyle='black';ctx.fillRect(0,0,c.width,c.height);if(maskUrl){const mask=new Image();mask.crossOrigin='anonymous';mask.onload=()=>ctx.drawImage(mask,0,0,c.width,c.height);mask.src=maskUrl}};base.src=imageUrl},[imageUrl,maskUrl]);
 function draw(event:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const c=canvas.current!,box=c.getBoundingClientRect(),ctx=c.getContext('2d')!,x=(event.clientX-box.left)*c.width/box.width,y=(event.clientY-box.top)*c.height/box.height;ctx.beginPath();ctx.arc(x,y,size*c.width/box.width,0,Math.PI*2);ctx.fillStyle=erase?'black':'white';ctx.fill()}
 async function save(){setBusy(true);canvas.current!.toBlob(async blob=>{if(blob)await onSave(new File([blob],'product-mask.png',{type:'image/png'}));setBusy(false)},'image/png')}
 return <div className="fixed inset-0 z-50 bg-black/60 p-5 grid place-items-center"><div className="bg-white rounded-2xl max-w-4xl w-full overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><div><b>商品蒙版编辑</b><p className="text-xs text-[var(--muted)]">白色保留商品，黑色作为背景。</p></div><button onClick={onClose}><X/></button></div><div className="grid md:grid-cols-2 gap-4 p-5 bg-[#eee]"><img src={imageUrl} className="w-full max-h-[65vh] object-contain bg-white"/><canvas ref={canvas} className="w-full max-h-[65vh] object-contain bg-black touch-none" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);draw(e)}} onPointerMove={draw} onPointerUp={()=>drawing.current=false}/></div><div className="p-4 flex flex-wrap items-center gap-3"><button className={`btn-secondary ${!erase?'ring-2 ring-emerald-300':''}`} onClick={()=>setErase(false)}>画笔补选</button><button className={`btn-secondary ${erase?'ring-2 ring-red-300':''}`} onClick={()=>setErase(true)}>橡皮擦除</button><label className="text-xs">画笔大小<input type="range" min="4" max="80" value={size} onChange={e=>setSize(Number(e.target.value))}/></label><button className="btn-primary ml-auto" disabled={busy} onClick={save}><Save size={14}/>{busy?'保存中':'保存蒙版'}</button></div></div></div>
}
