import { useEffect, useState } from 'react';
import { Check, Copy, FilePlus2, Loader2, Trash2 } from 'lucide-react';
import { creativeApi, operationsApi, productApi, templateApi } from '../api/client';
import type { CreativeProject, DetailPageTemplate, Product } from '../types';

export default function DetailTemplatesPage() {
  const [templates, setTemplates] = useState<DetailPageTemplate[]>([]);
  const [projects, setProjects] = useState<CreativeProject[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [sourceProject, setSourceProject] = useState('');
  const [name, setName] = useState('');
  const [target, setTarget] = useState<Record<number, string>>({});
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [recommendProduct,setRecommendProduct]=useState('');
  const [recommendations,setRecommendations]=useState<Array<{template_id:number;name:string;score:number;reasons:string[]}>>([]);
  const [performance,setPerformance]=useState<Record<number,{success_rate:number;adoption_rate:number;average_revision_rounds:number}>>({});
  async function load() { const [t, p, items] = await Promise.all([templateApi.list(), creativeApi.list(), productApi.list()]); setTemplates(t); setProjects(p); setProducts(items); const stats=await Promise.all(t.map(async x=>[x.id,await operationsApi.templatePerformance(x.id)] as const));setPerformance(Object.fromEntries(stats)); }
  useEffect(() => { load(); }, []);
  return <div className="space-y-6"><header><div className="text-xs text-[var(--accent)] font-medium">REUSABLE PRODUCTION</div><h1 className="font-display text-4xl mt-2">详情页模板库</h1><p className="text-sm text-[var(--muted)] mt-2">把已经验证过的模块结构保存下来，新商品只替换商品事实、卖点与素材。</p></header>
    {message && <div className="rounded-lg bg-emerald-50 text-emerald-800 px-4 py-3 text-sm flex gap-2"><Check size={16}/>{message}</div>}
    <section className="panel p-5"><h2 className="font-medium">智能推荐模板</h2><p className="text-xs text-[var(--muted)] mt-1">按品类、平台、品牌历史和商品形态排序。</p><div className="flex gap-3 mt-4"><select className="input flex-1" value={recommendProduct} onChange={async(e)=>{setRecommendProduct(e.target.value);setRecommendations(e.target.value?await operationsApi.recommendations(Number(e.target.value)):[])}}><option value="">选择商品查看推荐</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{recommendations.length>0&&<div className="grid md:grid-cols-3 gap-3 mt-4">{recommendations.slice(0,3).map((r,index)=><div className="rounded-xl bg-[var(--bg-elevated)] p-4" key={r.template_id}><div className="text-xs text-[var(--accent)]">推荐 {index+1} · 匹配 {r.score}%</div><div className="font-medium mt-1">{r.name}</div><div className="text-xs text-[var(--muted)] mt-2">{r.reasons.join(' · ')}</div><button className="btn-primary mt-3" onClick={async()=>{const p=await templateApi.apply(r.template_id,Number(recommendProduct));window.location.href=`/creative-projects/${p.id}/storyboard`}}>直接使用</button></div>)}</div>}</section>
    <section className="panel p-5"><h2 className="font-medium flex items-center gap-2"><FilePlus2 size={17}/>从现有项目保存模板</h2><div className="grid md:grid-cols-[1fr_1fr_auto] gap-3 mt-4"><select className="input" value={sourceProject} onChange={(e) => setSourceProject(e.target.value)}><option value="">选择已有详情页项目</option>{projects.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select><input className="input" placeholder="模板名称，例如：美妆水乳 16 屏标准结构" value={name} onChange={(e) => setName(e.target.value)}/><button className="btn-primary" disabled={!sourceProject || !name || busy} onClick={async () => { setBusy(true); try { await templateApi.save(Number(sourceProject), name); setName(''); setMessage('模板已保存，可以用于其他商品。'); await load(); } finally { setBusy(false); } }}>{busy ? <Loader2 size={14} className="animate-spin"/> : <FilePlus2 size={14}/>}保存模板</button></div></section>
    <section className="grid md:grid-cols-2 gap-4">{templates.map((item) => <article className="panel p-5" key={item.id}><div className="flex justify-between"><div><h2 className="font-medium">{item.name}</h2><div className="text-xs text-[var(--muted)] mt-1">{item.category || '通用品类'} · {item.platform} · {item.modules.length} 屏 · 已使用 {item.usage_count} 次</div></div><button className="text-red-600" onClick={async () => { if (confirm('停用这个模板？')) { await templateApi.remove(item.id); await load(); } }}><Trash2 size={15}/></button></div>{performance[item.id]&&<div className="grid grid-cols-3 gap-2 mt-4 text-center"><div className="rounded-lg bg-emerald-50 p-2"><b>{performance[item.id].success_rate}%</b><small className="block">完成率</small></div><div className="rounded-lg bg-blue-50 p-2"><b>{performance[item.id].adoption_rate}%</b><small className="block">采用率</small></div><div className="rounded-lg bg-amber-50 p-2"><b>{performance[item.id].average_revision_rounds}</b><small className="block">平均修改轮</small></div></div>}<div className="flex flex-wrap gap-1.5 mt-4">{item.modules.slice(0, 8).map((module, i) => <span key={i} className="rounded-full bg-[var(--bg-elevated)] px-2.5 py-1 text-[10px]">{String(module.title || '')}</span>)}{item.modules.length > 8 && <span className="text-xs text-[var(--muted)]">+{item.modules.length - 8}</span>}</div><div className="flex gap-2 mt-5"><select className="input flex-1" value={target[item.id] || ''} onChange={(e) => setTarget({ ...target, [item.id]: e.target.value })}><option value="">选择要套用的商品</option>{products.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="btn-primary" disabled={!target[item.id]} onClick={async () => { const project = await templateApi.apply(item.id, Number(target[item.id])); window.location.href = `/creative-projects/${project.id}/storyboard`; }}><Copy size={14}/>创建项目</button></div></article>)}{!templates.length && <div className="panel p-10 text-center text-sm text-[var(--muted)] md:col-span-2">还没有模板。先在详情页项目里完成策划，再从上方保存。</div>}</section>
  </div>;
}
