import { useEffect, useState } from 'react';
import { BarChart3, FileSpreadsheet, Loader2, RefreshCw, Square } from 'lucide-react';
import { productionApi, templateApi } from '../api/client';
import type { DetailPageTemplate } from '../types';

export default function ProductionHub(){
 const[templates,setTemplates]=useState<DetailPageTemplate[]>([]),[batches,setBatches]=useState<Array<{id:string;name:string;status:string;total:number;completed:number;failed:number}>>([]),[queue,setQueue]=useState<Array<{id:string;status:string;progress:number;total:number;attempt_count:number;error_message:string;payload:Record<string,unknown>}>>([]),[dashboard,setDashboard]=useState<{queue:Record<string,number>;throughput:Record<string,number>;efficiency:Record<string,number>;recent_batches:unknown[]}|null>(null),[file,setFile]=useState<File|null>(null),[name,setName]=useState('批量SKU生产'),[templateId,setTemplateId]=useState(''),[platform,setPlatform]=useState('天猫'),[busy,setBusy]=useState(false);
 const[preview,setPreview]=useState<{total:number;valid:number;invalid:number;issues:Array<{row:number;message:string}>}|null>(null);
 async function load(){const[t,b,q,d]=await Promise.all([templateApi.list(),productionApi.batches(),productionApi.queue(),productionApi.dashboard()]);setTemplates(t);setBatches(b);setQueue(q);setDashboard(d)}
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[]);
 return <div className="space-y-6"><header><div className="text-xs text-[var(--accent)] font-medium">PRODUCTION SYSTEM</div><h1 className="font-display text-4xl mt-2">批量生产与运营看板</h1><p className="text-sm text-[var(--muted)] mt-2">CSV批量创建SKU、持久化排队生成，并追踪产能和审核效率。</p></header>
 {dashboard&&<section className="grid md:grid-cols-4 gap-4">{[['待处理',dashboard.queue.pending||0],['生产中',dashboard.queue.running||0],['已定稿',dashboard.throughput.finalized||0],['一次通过率',`${dashboard.efficiency.first_pass_rate||0}%`]].map(([l,v])=><div className="panel p-5" key={String(l)}><BarChart3 size={17} className="text-[var(--accent)]"/><div className="text-2xl font-medium mt-3">{v}</div><div className="text-xs text-[var(--muted)]">{l}</div></div>)}</section>}
 <section className="panel p-5"><h2 className="font-medium flex items-center gap-2"><FileSpreadsheet size={17}/>导入CSV批量生产</h2><p className="text-xs text-[var(--muted)] mt-1">支持列：sku、name、category、brand_name、description、target_users、ingredients、usage_method、specifications、price、image_urls（多图用 | 分隔）。上传后先预检，不会立即创建商品。</p><div className="grid lg:grid-cols-[1fr_1fr_150px_180px_auto] gap-3 mt-4"><input className="input" value={name} onChange={e=>setName(e.target.value)}/><select className="input" value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">不使用模板，自动策划</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="input" value={platform} onChange={e=>setPlatform(e.target.value)}><option>天猫</option><option>京东</option><option>抖音</option><option>小红书</option></select><input type="file" accept=".csv,text/csv" className="input" onChange={async e=>{const f=e.target.files?.[0]||null;setFile(f);setPreview(f?await productionApi.previewBatch(f):null)}}/><button className="btn-primary" disabled={!file||busy||Boolean(preview?.invalid)} onClick={async()=>{if(!file)return;setBusy(true);try{await productionApi.importBatch(file,{name,template_id:Number(templateId)||undefined,platform,enqueue:true});setFile(null);setPreview(null);await load()}finally{setBusy(false)}}}>{busy?<Loader2 size={14} className="animate-spin"/>:<FileSpreadsheet size={14}/>}确认导入并排队</button></div>{preview&&<div className={`rounded-xl p-3 mt-3 text-sm ${preview.invalid?'bg-red-50 text-red-800':'bg-emerald-50 text-emerald-800'}`}>共 {preview.total} 行 · 可导入 {preview.valid} · 错误 {preview.invalid}{preview.issues.slice(0,10).map((i,index)=><div className="text-xs mt-1" key={index}>第 {i.row} 行：{i.message}</div>)}</div>}</section>
 <section className="grid lg:grid-cols-2 gap-5"><div className="panel overflow-hidden"><div className="p-5 border-b font-medium">生产批次</div><div className="divide-y">{batches.map(b=><div className="p-4" key={b.id}><div className="flex justify-between"><b className="text-sm">{b.name}</b><span className="text-xs">{b.status}</span></div><div className="text-xs text-[var(--muted)] mt-2">完成 {b.completed}/{b.total} · 失败 {b.failed}</div><div className="h-1.5 bg-[#eee] rounded mt-2"><div className="h-full bg-[var(--accent)] rounded" style={{width:`${b.total?(b.completed+b.failed)/b.total*100:0}%`}}/></div></div>)}</div></div><div className="panel overflow-hidden"><div className="p-5 border-b flex justify-between"><b>持久化任务队列</b><button onClick={load}><RefreshCw size={15}/></button></div><div className="divide-y max-h-[520px] overflow-auto">{queue.map(q=><div className="p-4" key={q.id}><div className="flex justify-between"><span className="text-sm">项目 #{String(q.payload.project_id||'')}</span><span className="text-xs">{q.status}</span></div><div className="text-xs text-[var(--muted)] mt-1">进度 {q.progress}/{q.total} · 尝试 {q.attempt_count}</div>{q.error_message&&<div className="text-xs text-red-700 mt-1">{q.error_message}</div>}{['pending','running'].includes(q.status)&&<button className="btn-secondary mt-2 text-xs" onClick={async()=>{await productionApi.cancelQueue(q.id);await load()}}><Square size={12}/>取消</button>}</div>)}</div></div></section>
 {dashboard&&<section className="panel p-5"><h2 className="font-medium">生产效率</h2><div className="grid md:grid-cols-5 gap-4 mt-4 text-center"><div><b className="text-xl">{dashboard.throughput.products||0}</b><small className="block">商品总数</small></div><div><b className="text-xl">{dashboard.throughput.projects||0}</b><small className="block">项目总数</small></div><div><b className="text-xl">{Math.round((dashboard.efficiency.average_time_to_first_reviewable_seconds||0)/60)}m</b><small className="block">首版可审核耗时</small></div><div><b className="text-xl">{Math.round((dashboard.efficiency.average_time_to_final_seconds||0)/60)}m</b><small className="block">平均定稿耗时</small></div><div><b className="text-xl">{dashboard.efficiency.average_review_rounds||0}</b><small className="block">平均审核轮数</small></div></div></section>}
 </div>
}
