import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Check,Save,ShieldCheck} from 'lucide-react';
import {creativeApi,qualityApi} from '../api/client';
import type {CanvasNodeRecord,CreativeProject} from '../types';

export default function QualityWorkbench(){
 const [projects,setProjects]=useState<CreativeProject[]>([]),[projectId,setProjectId]=useState(''),[nodes,setNodes]=useState<CanvasNodeRecord[]>([]),[category,setCategory]=useState('general');
 const [rules,setRules]=useState<{thresholds:Record<string,number>;rules:string[]}>({thresholds:{},rules:[]}),[comments,setComments]=useState<{original_count:number;merged_count:number;items:Array<any>}|null>(null),[todos,setTodos]=useState<{count:number;items:Array<any>}|null>(null),[message,setMessage]=useState('');
 const [versions,setVersions]=useState<Array<{version:number;snapshot:{thresholds:Record<string,number>;rules:string[]};created_at:string}>>([]),[samples,setSamples]=useState<Array<{id:number;name:string;case_type:string;accepted_url:string;failure_urls:string[];enabled:boolean}>>([]);
 useEffect(()=>{Promise.all([creativeApi.list(),qualityApi.reviewTodos()]).then(([p,t])=>{setProjects(p);setTodos(t)})},[]);
 useEffect(()=>{Promise.all([qualityApi.rules(category),qualityApi.ruleVersions(category),qualityApi.samples(category)]).then(([r,v,s])=>{setRules(r);setVersions(v);setSamples(s)})},[category]);
 useEffect(()=>{if(!projectId)return;Promise.all([creativeApi.nodes(Number(projectId)),qualityApi.mergedComments(Number(projectId))]).then(([n,c])=>{setNodes(n.filter(x=>Boolean(x.data.image_url)));setComments(c)})},[projectId]);
 async function correct(node:CanvasNodeRecord,type:string){const note=prompt('请说明AI质检判断的问题')||'';if(!note)return;await qualityApi.feedback(Number(projectId),node.id,{feedback_type:type,note});if(type==='false_negative'){await qualityApi.createSample({category,case_type:String(node.data.module_role||'general'),name:`失败样本·${String(node.data.label||node.id)}`,accepted_url:'',input_urls:[],failure_urls:[String(node.data.image_url||'')]});setSamples(await qualityApi.samples(category))}setMessage(type==='false_negative'?'已记录漏报并加入失败回归样本':'质检纠错已记录')}
 return <div className="space-y-6"><header><div className="text-xs font-medium text-[var(--accent)]">QUALITY CONTROL</div><h1 className="font-display text-4xl mt-2">质量与审核工作台</h1><p className="text-sm text-[var(--muted)] mt-2">管理品类阈值、纠正AI质检、合并审核意见和跟进待办。</p></header>{message&&<div className="rounded-lg bg-emerald-50 text-emerald-800 p-3 text-sm">{message}</div>}
 <section className="panel p-5"><div className="flex items-end gap-3"><label className="text-xs flex-1">品类<input className="input block w-full mt-1" value={category} onChange={e=>setCategory(e.target.value)}/></label><button className="btn-primary" onClick={async()=>{await qualityApi.saveRules(category,rules);setMessage('品类质检规则已发布新版本')}}><Save size={14}/>保存规则</button></div><div className="grid md:grid-cols-3 gap-3 mt-4">{Object.entries(rules.thresholds).map(([key,value])=><label className="text-xs" key={key}>{key}<input className="input w-full mt-1" type="number" min="0" max="100" value={value} onChange={e=>setRules({...rules,thresholds:{...rules.thresholds,[key]:Number(e.target.value)}})}/></label>)}</div><label className="text-xs block mt-4">品类检查规则<textarea className="input w-full min-h-28 mt-1" value={rules.rules.join('\n')} onChange={e=>setRules({...rules,rules:e.target.value.split('\n').filter(Boolean)})}/></label></section>
 {versions.length>0&&<section className="panel p-5"><h2 className="font-medium">质检规则版本</h2><div className="flex flex-wrap gap-2 mt-3">{versions.map(version=><button className="btn-secondary" key={version.version} onClick={async()=>{const next=await qualityApi.rollbackRules(category,version.version);setRules({thresholds:next.thresholds,rules:next.rules});setVersions(await qualityApi.ruleVersions(category));setMessage(`已回滚到 v${version.version}，并发布新版本`)}}>v{version.version} · {new Date(version.created_at).toLocaleString()}</button>)}</div></section>}
 <section className="panel p-5"><h2 className="font-medium">回归样本库</h2><div className="space-y-2 mt-3">{samples.map(sample=><div className="rounded-lg border p-3 flex items-center gap-3" key={sample.id}><div className="flex-1"><b className="text-sm">{sample.name}</b><div className="text-xs text-[var(--muted)]">{sample.case_type} · 失败样本 {sample.failure_urls?.length||0}</div></div><button className="btn-secondary" onClick={async()=>{await qualityApi.updateSample(sample.id,{enabled:!sample.enabled});setSamples(await qualityApi.samples(category))}}>{sample.enabled?'停用':'启用'}</button><button className="btn-secondary text-red-700" onClick={async()=>{await qualityApi.deleteSample(sample.id);setSamples(await qualityApi.samples(category))}}>删除</button></div>)}</div></section>
 <section className="panel p-5"><h2 className="font-medium">审核待办（{todos?.count||0}）</h2><div className="grid md:grid-cols-2 gap-2 mt-3">{todos?.items.map(item=><div className="rounded-lg bg-[var(--bg-elevated)] p-3 text-sm" key={item.project_id}><b>{item.name}</b><span className="ml-2 text-[var(--muted)]">{item.action} · {item.open_issues}项问题</span></div>)}</div></section>
 <section className="panel p-5"><label className="text-xs">选择项目<select className="input w-full mt-1" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">请选择</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{comments&&<div className="mt-4"><div className="text-sm font-medium">意见自动合并：{comments.original_count} 条 → {comments.merged_count} 组</div><div className="space-y-2 mt-2">{comments.items.map((item,index)=><div className="rounded-lg bg-amber-50 p-3 text-xs" key={index}><b>{item.issue_type}</b> · {item.severity}<div className="mt-1">{item.notes.join('；')}</div><Link className="text-[var(--accent)] inline-block mt-2" to={`/creative-projects/${projectId}/storyboard#module-${item.module_id}`}>定位到问题页面</Link></div>)}</div></div>}</section>
 {projectId&&<section className="panel p-5"><h2 className="font-medium flex items-center gap-2"><ShieldCheck size={16}/>质检结果人工纠错</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{nodes.map(node=><div className="rounded-xl border border-[var(--border)] p-3" key={node.id}><div className="text-sm font-medium">{String(node.data.label||node.id)}</div><div className="text-xs text-[var(--muted)] mt-1">视觉质检：{node.data.vision_quality?'已运行':'未运行'}</div><div className="flex flex-wrap gap-1.5 mt-3"><button className="btn-secondary text-xs" onClick={()=>correct(node,'false_positive')}>AI误报</button><button className="btn-secondary text-xs" onClick={()=>correct(node,'false_negative')}>AI漏报</button><button className="btn-secondary text-xs" onClick={()=>correct(node,'wrong_field')}>类型错误</button><button className="btn-secondary text-xs" onClick={()=>correct(node,'wrong_score')}>分数不合理</button><button className="btn-secondary text-xs" onClick={async()=>{await qualityApi.createSample({category,case_type:String(node.data.module_role||'general'),name:String(node.data.label||'回归样本'),accepted_url:String(node.data.image_url||''),input_urls:[],failure_urls:[]});setMessage('已加入回归基准库')}}><Check size={13}/>加入合格样本</button></div></div>)}</div></section>}
 {projectId&&nodes.some(node=>Boolean(node.data.protected_text_check))&&<section className="panel p-5"><h2 className="font-medium">Logo / 包装文字核对</h2><div className="space-y-3 mt-3">{nodes.filter(node=>Boolean(node.data.protected_text_check)).map(node=>{const check=node.data.protected_text_check as {status:string;matches?:Array<{expected:string;observed:string;same:boolean;confidence:number}>;issues?:string[]};return <div className="rounded-xl border p-3" key={node.id}><div className="flex justify-between text-sm"><b>{String(node.data.label||node.id)}</b><span>{check.status}</span></div>{check.matches?.map((match,index)=><div className={`text-xs mt-2 rounded p-2 ${match.same?'bg-emerald-50':'bg-red-50'}`} key={index}>标准：{match.expected||'未识别'} → 生成：{match.observed||'未识别'} · {Math.round((match.confidence||0)*100)}%</div>)}{check.issues?.length?<div className="text-xs text-red-700 mt-2">{check.issues.join('；')}</div>:null}</div>})}</div></section>}
 </div>
}
