import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Activity, CheckCircle2, Coins, Eye, Loader2, RefreshCw, Search, Square } from 'lucide-react';
import { creativeApi, creativeMetricsApi, operationsApi } from '../api/client';
import type { CreativeMetrics } from '../api/client';
import type { CreativeProject } from '../types';
const empty={project_id:'',provider:'',status:'',date_from:'',date_to:'',error_code:''};
const errorLabels:Record<string,string>={unknown:'未识别原因',provider_error:'服务商错误',insufficient_balance:'账户余额不足',interrupted:'任务中断'};
const errorTone=(code:string)=>code==='unknown'?'bg-stone-100 text-stone-600':code==='interrupted'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700';
export default function TaskCenterPage(){
 const[searchParams]=useSearchParams();
 const initialFilters={...empty,project_id:searchParams.get('project_id')||'',status:searchParams.get('status')||''};
 const[data,setData]=useState<CreativeMetrics|null>(null),[projects,setProjects]=useState<CreativeProject[]>([]),[filters,setFilters]=useState(initialFilters),[selected,setSelected]=useState<number[]>([]),[detail,setDetail]=useState<Record<string,unknown>|null>(null),[stats,setStats]=useState<{error_breakdown:Record<string,number>;average_duration_ms:number;p95_duration_ms:number;cancelled:number}|null>(null),[billing,setBilling]=useState<{configured:boolean;source:string;record_count:number;amount_cny:number;latest_date:string|null}|null>(null),[busy,setBusy]=useState(false);
 async function load(next=filters){const params=Object.fromEntries(Object.entries(next).filter(([,v])=>v));const[d,s,b]=await Promise.all([creativeMetricsApi.summary(params),operationsApi.taskStatistics(params),operationsApi.billingStatus()]);setData(d);setStats(s);setBilling(b)}
 useEffect(()=>{Promise.all([load(initialFilters),creativeApi.list().then(setProjects)])},[]);
 if(!data)return <div className="h-64 grid place-items-center"><Loader2 className="animate-spin"/></div>;
 const cards=[['总任务',data.total_tasks,Activity],['成功率',`${data.success_rate}%`,CheckCircle2],['平均耗时',`${Math.round((stats?.average_duration_ms||0)/1000)}s`,Activity],[billing?.source==='provider_bill'?'真实费用':'估算费用',`¥${billing?.source==='provider_bill'?billing.amount_cny:data.estimated_cost_cny}`,Coins]] as const;
 async function batch(action:'retry'|'cancel'){setBusy(true);try{if(action==='retry')await operationsApi.retryTasks(selected);else await operationsApi.cancelTasks(selected);setSelected([]);await load()}finally{setBusy(false)}}
 return <div className="space-y-6"><header><div className="text-xs text-[var(--accent)] font-medium">OPERATIONS</div><h1 className="font-display text-4xl mt-2">任务与费用中心</h1><p className="text-sm text-[var(--muted)] mt-2">任务详情、批量操作、错误统计、耗时和真实账单同步。</p></header>
 <section className="panel p-4"><div className="grid md:grid-cols-6 gap-3"><select className="input" value={filters.project_id} onChange={e=>setFilters({...filters,project_id:e.target.value})}><option value="">全部项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" value={filters.provider} onChange={e=>setFilters({...filters,provider:e.target.value})}><option value="">全部模型</option>{data.providers.map(p=><option key={p}>{p}</option>)}</select><select className="input" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部状态</option><option value="attention">需要处理</option><option value="completed">成功</option><option value="failed">失败</option><option value="running">运行中</option><option value="cancelled">已取消</option></select><input className="input" type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/><input className="input" type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/><button className="btn-primary" onClick={()=>load()}><Search size={14}/>筛选</button></div>{filters.error_code&&<div className="mt-3 text-xs text-[var(--muted)]">失败原因：<button className="rounded-full bg-red-50 text-red-700 px-2 py-1" onClick={()=>{const next={...filters,error_code:''};setFilters(next);load(next)}}>{errorLabels[filters.error_code]||filters.error_code} ×</button></div>}</section>
 <div className="grid sm:grid-cols-4 gap-4">{cards.map(([l,v,I])=><div className="panel p-5" key={l}><I size={17} className="text-[var(--accent)]"/><div className="text-2xl font-medium mt-4">{v}</div><div className="text-xs text-[var(--muted)] mt-1">{l}</div></div>)}</div>
 <section className="grid lg:grid-cols-2 gap-4"><div className="panel p-5"><div className="flex justify-between"><b>火山方舟账单</b><button className="btn-secondary" title={billing?.configured?'同步真实账单':'未配置账单 API 凭证'} disabled={!billing?.configured||busy} onClick={async()=>{setBusy(true);try{await operationsApi.syncBilling();await load()}finally{setBusy(false)}}}><RefreshCw size={14}/>同步</button></div><p className="text-xs text-[var(--muted)] mt-2">{billing?.configured?billing.source==='provider_bill'?`已同步 ${billing.record_count} 条，最近 ${billing.latest_date}`:'已配置，尚未拉到账单记录':'未配置账单 API 凭证，同步功能暂不可用；当前继续显示估算费用'}</p></div><div className="panel p-5"><b>任务运行统计</b><div className="grid grid-cols-3 gap-2 mt-3 text-center text-sm"><div>平均<br/><b>{Math.round((stats?.average_duration_ms||0)/1000)}s</b></div><div>P95<br/><b>{Math.round((stats?.p95_duration_ms||0)/1000)}s</b></div><div>取消<br/><b>{stats?.cancelled||0}</b></div></div><div className="mt-4"><div className="text-xs text-[var(--muted)] mb-2">历史失败原因 · 仅统计当前筛选范围，不代表服务当前异常</div>{Object.keys(stats?.error_breakdown||{}).length===0?<div className="text-xs text-emerald-700">当前筛选范围内无失败任务</div>:<div className="flex flex-wrap gap-2">{Object.entries(stats?.error_breakdown||{}).map(([k,v])=><button className={`rounded-full px-2.5 py-1 text-xs ${errorTone(k)}`} title="点击查看对应任务" key={k} onClick={()=>{const next={...filters,error_code:k};setFilters(next);load(next)}}>{errorLabels[k]||k} {v}</button>)}</div>}</div></div></section>
 {selected.length>0&&<div className="panel p-3 flex items-center gap-3"><span className="text-sm">已选择 {selected.length} 项</span><button className="btn-secondary" disabled={busy} onClick={()=>batch('retry')}><RefreshCw size={14}/>批量重试失败项</button><button className="btn-secondary" disabled={busy} onClick={()=>batch('cancel')}><Square size={14}/>取消运行项</button></div>}
 <section className="panel overflow-hidden"><div className="p-5 border-b font-medium">生成任务明细（{data.recent_tasks.length}）</div><div className="divide-y">{data.recent_tasks.map(t=>{const projectName=projects.find(p=>p.id===t.project_id)?.name||`项目 #${t.project_id}`;return <div key={t.id} className="p-4 grid md:grid-cols-[30px_60px_1.2fr_110px_100px_1.5fr_auto] gap-3 items-center text-sm"><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(x=>x!==t.id))}/><span>#{t.id}</span><span>{t.action}<small className="block text-[var(--muted)] truncate">{projectName}</small></span><span>{t.provider}</span><span className={t.status==='failed'||t.status==='interrupted'?'text-red-700':t.status==='completed'?'text-emerald-700':'text-amber-700'}>{t.status}</span><span className="text-xs"><span className="block">{t.diagnostic?.title||`${t.result_count} 张`}</span><span className="block text-[var(--muted)]">{t.triggered_by} · {new Date(t.created_at).toLocaleString()}</span></span><button className="btn-secondary" onClick={async()=>setDetail(await operationsApi.taskDetail(t.id))}><Eye size={14}/>详情</button></div>})}</div></section>
 {detail&&<div className="fixed inset-0 z-50 bg-black/55 p-5" onClick={()=>setDetail(null)}><div className="max-w-2xl mx-auto bg-white rounded-2xl p-6 max-h-[85vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-medium text-lg">任务 #{String(detail.id)}</h2><button onClick={()=>setDetail(null)}>关闭</button></div><div className="grid grid-cols-2 gap-3 text-sm mt-5"><div>状态：{String(detail.status)}</div><div>耗时：{Math.round(Number(detail.duration_ms||0)/1000)} 秒</div><div>模型：{String(detail.provider)}</div><div>项目：#{String(detail.project_id)}</div></div><pre className="mt-4 text-xs whitespace-pre-wrap rounded-xl bg-[var(--bg-elevated)] p-4">{JSON.stringify(detail.context_snapshot,null,2)}</pre></div></div>}
 </div>}
